services:
  - type: web
    name: splitease
    env: node
    region: oregon
    plan: free
    buildCommand: "cd server && npm install && cd ../client && npm install && npm run build"
    startCommand: "cd server && node index.js"
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
